pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url 'https://repo1.maven.org/maven2' }
        maven { url 'https://artifact.bytedance.com/repository/pangle/' }
        maven { url 'https://android-sdk.is.com/' }
        maven { url = uri("https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea") }
        maven {
            url = uri('https://maven.pkg.github.com/anr-2609/fireants-ad-sdk')

            credentials {
                username = providers.gradleProperty('gpr.user').orNull
                password = providers.gradleProperty('gpr.key').orNull
            }
        }
    }
}

rootProject.name = "fireants-dev-config"
include ':devConfig'
